# Site settings
title: Welcome to Jinki's Website
name: Jinki Lee
email: jinkilee552@gmail.com
linkedin: https://www.linkedin.com/feed/
github: https://github.com/jinki-lee
description: "Jinki Lee's Blog / Resume."

# Build settings
remote_theme: jekyll/minima
